name: Generate Snake

on:
  # Trigger the action every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Allow manual triggering from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build:
    # Using windows-latest runner for Windows compatibility
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Python (required for generating snake)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python 3.x version

      # Step 3: Install dependencies (necessary for the snake generation script)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib numpy Pillow

      # Step 4: Generate the snake contribution grid (GIF and SVG)
      - name: Generate Snake GIF and SVG
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: papali1305  # Your GitHub username
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Step 5: Debugging: Check if the files are generated successfully
      - name: List Generated Files
        run: dir dist  # For Windows, using 'dir' instead of 'ls'

      # Step 6: Commit and push the changes to the "output" branch
      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "Generated snake GIF and SVG"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Optional: Deploy to GitHub Pages (if needed)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # The branch where the snake files will be deployed
          build_dir: dist         # Directory of the generated snake files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
